# Base image
FROM python:3.12-slim

# Set working dir
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt


# Copy source code
COPY src/ src/


# Create artifacts dir
RUN mkdir -p artifacts

# Default command: run training pipeline
CMD ["python", "-m", "src.pipeline.run_pipeline"]